<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="description" content="Site de jeux et d'activités pour jeune enfants">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" >
	<title>Apprendre avec Miaou</title>
	<link rel="stylesheet" href="style.css">
</head>
<body>
    <header class="header">
        <img src="../assets/img/chatFiligranne.png"></img>
        <h1>Apprendre avec Miaou</h1>
            <nav>
                <ul>
                    <li>
                        <a href="index.php?route=login">Login</a>
                    </li>
                    <li>
                        <a href="index.php?route=register">Register</a>
                    </li>
                    <li>
                        <a href="index.php?route=profile">Profile</a>
                    </li>
                    <li>
                        <a href="index.php?route=logout">Logout</a>
                    </li>
                </ul>
            </nav>
    </header>
    <main class="container"></main>
    <footer class="footer"></footer>
    
</body>
</html>